# Generated by Django 4.2.5 on 2024-02-16 20:58

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='cat', unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description_of_category', models.TextField(max_length=10000)),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('updated_of_category', models.DateTimeField(blank=True, null=True)),
                ('image_category', models.ImageField(default='category.jpg', upload_to='image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Libel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description_of_libel', models.TextField(max_length=1000)),
                ('colors_choice_for_libel', models.CharField(choices=[('orange', 'Orange'), ('white', 'White'), ('black', 'Black'), ('pink', 'Pink'), ('blue', 'Blue'), ('green', 'Green')], default='white', max_length=10)),
            ],
            options={
                'verbose_name': 'Libel',
                'verbose_name_plural': 'libels',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('image', models.ImageField(default='note.jpg', upload_to='image')),
                ('is_tasks', models.BooleanField()),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('updated_of_note', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='apps.category')),
                ('libel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.libel')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
