# Generated by Django 5.0.1 on 2024-02-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='bgColor',
            field=models.CharField(default='rgb(249 115 22 / var(--tw-bg-opacity))', max_length=40),
        ),
    ]
