# Generated by Django 5.0.1 on 2024-02-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='user.png', upload_to='profile', verbose_name='Photo de Profil'),
        ),
    ]
