# Generated by Django 5.0.1 on 2024-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
    ]
