# Generated by Django 5.0.1 on 2024-02-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_notes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='bgColor',
            field=models.CharField(default='rgb(249 115 22 / var(--tw-bg-opacity))', max_length=30),
        ),
    ]
