# Generated by Django 5.0.1 on 2024-02-19 22:40

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_notes_bgcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uuid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345678', length=10, max_length=30, prefix='note', unique=True),
        ),
    ]
